import fs from 'node:fs';
import path from 'node:path';
import {root,readJSON,fresh} from '../lib/files.mjs';
import {assess} from '../lib/assess.mjs';
import {conflicts} from '../lib/claims.mjs';
const run=process.argv[2];
if(!run||!/^results\/local-[a-zA-Z0-9-]+$/.test(run))throw new Error('Pass the local result directory');
const records=readJSON('work/content/records.json'),claims=readJSON('work/content/claims.json');
const systems=Object.fromEntries(['structured','keyword','orderedRaw'].map(name=>[name,fs.readFileSync(path.join(root,run,(name==='keyword'?'lexical':name)+'.jsonl'),'utf8').trim().split(/\r?\n/).map(JSON.parse)]));
const summary=readJSON(run+'/summary.json');
const initial=records.find(r=>assess(r).status==='failed' && conflicts(assess(r),claims.find(c=>c.recordId===r.recordId).replies).length)?.recordId??records[0].recordId;
const data={records,claims,systems,summary,initialRecord:initial};
const json=JSON.stringify(data).replaceAll('<','\\u003c').replaceAll('>','\\u003e').replaceAll('&','\\u0026');
const html=fs.readFileSync(path.join(root,'app/ui/index.template.html'),'utf8').replace('__DESK_DATA__',json);
fresh('public/demo.html',html);
fresh('public/content/records.json',records);
fresh('public/content/claims.json',claims);
fresh('public/content/sanity.ndjson',fs.readFileSync(path.join(root,'work/content/sanity.ndjson'),'utf8'));
fresh('public/content/manifest.json',readJSON('work/content/manifest.json'));
fresh('public/results/summary.json',summary);
for(const [name,predictions]of Object.entries(systems))fresh('public/results/'+(name==='keyword'?'lexical':name)+'.jsonl',predictions.map(p=>JSON.stringify(p)).join('\n')+'\n');
console.log('DEMO BUILT: public/demo.html; 48 records, exact copied receipts, historical replies, and all three local comparisons.');
console.log('No labels, secrets, remote scripts, or network connections are embedded.');
