import fs from 'node:fs';
import path from 'node:path';
import {root,readJSON,fresh,stamp} from '../lib/files.mjs';
const paths=fs.readdirSync(path.join(root,'results')).filter(x=>fs.statSync(path.join(root,'results',x)).isDirectory());
const current=paths.filter(x=>x.startsWith('context-')&&!x.startsWith('context-check-')).reverse().find(x=>fs.existsSync(path.join(root,'results',x,'summary.json')));
const kb=paths.filter(x=>x.startsWith('knowledge-base-')).reverse().find(x=>fs.existsSync(path.join(root,'results',x,'receipt.json')));
const checks=[];
checks.push({part:'local candidate',status:fs.existsSync(path.join(root,'public/demo.html'))?'done':'unknown'});
let live=null;if(current)live=readJSON('results/'+current+'/summary.json');
checks.push({part:'Context evaluation',status:live?.provider==='sanity-context'&&live.status==='done'&&live.systems.structured.total===48&&live.systems.structured.invalid===0?'done':'unknown'});
checks.push({part:'Knowledge Base retrieval',status:kb&&readJSON('results/'+kb+'/receipt.json').status==='done'?'done':'unknown'});
const ai=fs.existsSync(path.join(root,'results/ai-harness-summary.json'))?readJSON('results/ai-harness-summary.json'):null;
checks.push({part:'AI harness',status:ai?.status==='done'&&ai.records===48&&ai.provider&&ai.receiptFile?'done':'unknown'});
const review=fs.existsSync(path.join(root,'REVIEW-ACCEPTED.md'))?fs.readFileSync(path.join(root,'REVIEW-ACCEPTED.md'),'utf8'):'';
checks.push({part:'human review',status:review.includes('REVIEW ACCEPTED')?'done':'unknown'});
const post=fs.readFileSync(path.join(root,'POST-DRAFT.md'),'utf8');
checks.push({part:'final post',status:!post.includes('[Joshua:')&&/https:\/\/github\.com\//.test(post)?'done':'partial'});
const all=checks.every(c=>c.status==='done');
fresh('results/readiness-'+stamp()+'.json',{status:all?'done':'partial',readyToPost:all,checks});
console.log(all?'READY FOR OWNER REVIEW: required saved evidence is present.':'NOT READY TO POST: '+checks.filter(c=>c.status!=='done').map(c=>c.part).join(', ')+'.');
for(const c of checks)console.log(c.part+': '+c.status);
if(!all)process.exitCode=2;
